name: Folder check

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: MiSTer folder integrity
      run: ./.github/folder_check.sh

